version: "3"

services:
  otrs-server:
    image: jniltinho/otrs-server:6.0.30
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /opt/otrs:/opt/otrs

  mysql:
    image: mariadb:11.3.2-jammy
    restart: always
    ports:
      - '3306:3306'
    environment:
      - TZ=America/Sao_Paulo
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - MYSQL_USER=otrs
      - MYSQL_PASSWORD=otrs
      - MYSQL_ROOT_PASSWORD=root
    command: 
      - --table_definition_cache=800
      - --explicit_defaults_for_timestamp=true
      - --max_connections=800
    volumes:
      - ./dbdata:/var/lib/mysql
      #- "./init1.sql:/docker-entrypoint-initdb.d/init1.sql"
